// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqjblurgygwadtfadpjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxamJsdXJneWd3YWR0ZmFkcGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjU5ODIsImV4cCI6MjA2MjcwMTk4Mn0.gq8wG8Ikwm1aCDXfCLZTMTlbosRdv6a1EWtuA60ykaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);